config/routes.rb
Rails.application.routes.draw do


  get 'welcome/index'



devise_for :users, :controllers => { registrations: 'registrations' }, :path => '', :path_names => {:sign_in => 'login', :sign_up => 'signup', :sign_out => 'logout'}

  resources :users do
    resources :posts
    member do
      get :following, :followers, :edit_photo
    end
  end




  resources :relationships,  only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]

  

  get 'edit_photo', to: 'users#edit_photo'

  get 'friends_posts', to: 'relationships#index'

  post 'posts/show', to: 'comments#create'
   root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  extend FriendlyId
  
  friendly_id :full_name, use: [:slugged, :finders]
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :comments
  
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  has_many :followers, through: :passive_relationships, source: :follower
  
  

  
  
  #validations
  validates :first_name, :last_name, :email, presence: true
  
  validates :email, uniqueness: true
  
  validates :introduction, length: { maximum: 500 } 
  
  #paperclip
  has_attached_file :avatar, styles: { large:"600x600#", medium: "250x250#", thumb: "50x50#" }, default_url: "/images/missing_:style.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  #valdiations for paperclip
  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 2.megabytes
  
  
  def full_name
    "#{self.first_name} #{self.last_name}"
  end
  
  
  
  #start the following stuff
  def following?(other_user)
    following.include?(other_user)
  end
  
  def being_followed?(other_user)
    followers.include?(other_user)
  end
  
     # Follows a user
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:new, :index, :show, :create, :sign_in]
  load_and_authorize_resource except: [:following, :followers ]

  def index
    if params[:q]
      search_term = params[:q]
      @users = User.where("((first_name || ' ' || last_name) ilike ?) OR (first_name ilike ?) OR (last_name ilike ?)", "%#{search_term}%", "%#{search_term}%", "%#{search_term}%")
    else
      @users = User.order(email: :asc)
    end
  end

  def show
    @user = User.friendly.find(params[:id])
    if @user == current_user
        redirect_to edit_user_path(current_user.to_param)
    end
    @posts = @user.posts.all.order("created_at DESC").paginate(page: params[:posts_page], per_page: 4)

  end

  def new
    @user = User.new
  end

  def edit

    @user = current_user
    @posts = @user.posts.all.order("created_at DESC").paginate(page: params[:posts_page], per_page: 4)
    @comments = @user.comments.all.order("created_at DESC").paginate(page: params[:comments_page], per_page: 4)
  end

  def create
    @user= User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created'
    else
      redirect_to root_path, alert: 'User not created'
    end
  end


  def update
    @user = User.friendly.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'User successfully updated'
    else
      redirect_to edit_user_path, alert: 'User not updated. Please try again.'
    end
  end

  def destroy
    @user = User.friendly.find(params[:id])
    @user.destroy
    redirect_to root_path, alert: "User has been erased. Goodbye!"

  end

  def edit_photo
    @user = current_user
  end

  def following
    @title = "Following"
    @user  = User.friendly.find(params[:id])
    @users = @user.following.paginate(page: params[:page], per_page: 4)
    @following = true
    render '/shared/_show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.friendly.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 4)
    @following = false
    render '/shared/_show_follow'
  end




    private

      def user_params
        params.require(:user).permit(:email, :password, :avatar, :first_name, :last_name, :introduction)
      end

end

app/helpers/users_helper.rb
module UsersHelper
  
  #Remove time from post creation, leaving only date
  def remove_time(comment_or_post)
    date = comment_or_post.created_at.to_s.slice(0..9)
    return date
  end
  
end

app/views/users/_table.html.erb
<table class="table table-bordered table-striped">
        <thead>
          <tr>
            <td class="garamond" colspan="2" style="font-size:20px;">Most Recent Posts</td>
          </tr>
        </thead>
        <tbody>
          
          <% @posts.each do |post| %>
          <tr>
            <td><%=link_to post.title, post_path(post.id) %></td>
            <td><%= remove_time(post)%></td>
          </tr>
          
  <% end %>
 
        </tbody>
        
      </table>
<%= will_paginate @posts, page_links: false, class: "digg_pagination" %>

app/views/users/_user.html.erb
      <tr>
        <td>
          <%= link_to user, class: "thumb-link" do%>
          <%= image_tag user.avatar(:thumb), class: "img-circle thumb" %>
          <%end%>
        </td>
        <td>
          <%= user.full_name %>
        </td>
        <% if @following ==true %>
        <td>
          <% if @user == current_user %>
              <%= link_to 'UnFollow', relationship_path(current_user.active_relationships.find_by(followed_id: user.id)),
                  method: :delete, class: "btn btn-md btn-warning" %>
          <% end %>
          
        </td>
        <% end %>
    </tr>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= content_for(:body_attributes) do %>data-no-turbolink="true"<% end %>

<section class="container">
  
  
  <div class="row">
    <div class="col-sm-6 col-xs-12" id="photo-holder">
      <div id="profile-edit-photo">
        <%= link_to edit_photo_user_path(current_user) do %>
          <%= image_tag @user.avatar(:medium), id: "profile", class: "img-circle img-responsive", data: { toggle: 'tooltip', placement: "right" }, title: "Change profile photo" %>
        <% end %>
        <span class="glyphicon glyphicon-camera"></span>
      </div>
    </div>
      <div class="col-sm-6 col-xs-12">
        <h1 class="profile-name"><%=@user.full_name %></h1>
        <div id ="following"> 
          <div class="stats">
            <strong class="stat">
              <%= link_to following_user_path(@user.id) do %>
                <%= @user.following.count %>
              <% end %>
            </strong>
              Following |
            <strong class="stat">
              <%= link_to followers_user_path(@user.id) do %>
                <%= @user.followers.count %>
              <% end %>
            </strong>
            Followers
          </div>
        </div>
        <hr class="profile-break">
        <div class="edit-profile-link">
          <p class="noto-serif"><%= @user.introduction %></p>
          <%= link_to 'Edit Profile', edit_user_registration_path, class: "btn btn-lg btn-primary" %>
        </div>
        </div>
    <div class="col-xs-12">
      
      <ul class="profile-list">
        <li><%=link_to 'Find Users', users_path, class: "btn btn-default" %></li>
        <li><%=link_to "Following Posts", friends_posts_path, class: "btn btn-default" %></li>
      </ul>
      
      <!-- form for profile introduction -->
      <% if @user.introduction.blank? %>
        <%= form_for @user do |form| %>
          <div class= "form-group">
            <%= form.text_area :introduction, class: "form-control", maxlength: 500, id: "intro-form", placeholder: "Enter your intro here..." %>
          </div>
          <div class="text-center">
          <%= form.submit 'Submit Intro', class: "btn btn-default", id:"submit-intro", data: { no_turbolink: true } %>
        </div>
          <% end %>
      <% end %>
      
      <!-- begin tables for posts and comments -->
      <% unless @posts.empty? %>
        <%= render 'shared/table' %>
      <% else %>
        <p class="text-center">You do not yet have any posts to display.</p>
      <% end%>
      <% unless @comments.empty? %>
        <%= render 'shared/recent_comments_table' %>
      <% else %>
        <p class="text-center">You do not yet have any comments to display.</p>
      <% end%>
    </div>
  </div>
</section>
<script>
  $( window ).load(function() {
 //place camera icon inside users#edit image tactfully by changing div size
    function camera_icon() {
      var image_width = $("#profile").width();
      var image_height  = $("#profile").height();
      
    
      
      $("#profile-edit-photo").css({'height': image_height, "width": image_width});
      
    }
    
    
    
    //The load event is sent to an element when it and all sub-elements have been completely loaded
    camera_icon();
  });
</script>

app/views/users/edit_photo.html.erb
<section class="container text-center">
  <h1 class="text-center">Change your Profile Photo</h1>
   <%= image_tag @user.avatar(:medium), id: "profile" %>
   </br>
   <i>Photo must be under 2MB</i>
   <%= form_for @user, html: { multipart: true } do |form| %>
  <%= form.file_field :avatar %>
  <%= form.submit 'Submit Image', class: "btn btn-primary", id:"submit-edit", data: { no_turbolink: true } %> 
<% end %>
   
</section>

app/views/users/index.html.erb
<section class="container">
   
   <% if user_signed_in? %>
     <%= form_tag("/users", method: "get", class: "form-group text-center") do %> 
       <%= text_field_tag(:q, "Search Users", class: "form-control search-form", style: "max-width:250px;") %>
       <%= submit_tag 'Search', class: "btn form-group" %>
     <% end %>
   <% end %>
   
  <div class= "row">        
    <% @users.each  do |user|%>
      <div class="col-xs-6 col-md-4">
        <%= link_to user_path(user.id), class: "thumb-link " do%>
          <%= image_tag user.avatar(:thumb), class: "img-circle thumb user-index" %>
        <%end%>
        <%= link_to user.full_name, user_path(user), class: "info-pad user-index-link" %>
      </div>
    
  <% end %>
  </div>
    
</section>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<section class="container">
  
  
  <div class="row">
    <div class="col-sm-6 col-xs-12">
<%=image_tag @user.avatar(:medium), class: "profile img-circle img-responsive" %>
    </div>
    <div class="col-sm-6 col-xs-12">
      <h1 class="profile-name"><%=@user.full_name%></h1>
      <div id ="following"> <!-- for Ajax-->
<%=render 'shared/follow' %>
      </div>
    </div>
    <div class="col-xs-12">
      <% unless @posts.empty? %>
        <%=render 'shared/table' %>
      <% else %>
        <p class="text-center">This user does not have any posts to display</p>
      <% end %>
    </div>
  </div>
  
</section>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>