config/routes.rb
Rails.application.routes.draw do


  get 'welcome/index'



devise_for :users, :controllers => { registrations: 'registrations' }, :path => '', :path_names => {:sign_in => 'login', :sign_up => 'signup', :sign_out => 'logout'}

  resources :users do
    resources :posts
    member do
      get :following, :followers, :edit_photo
    end
  end




  resources :relationships,  only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]

  

  get 'edit_photo', to: 'users#edit_photo'

  get 'friends_posts', to: 'relationships#index'

  post 'posts/show', to: 'comments#create'
   root 'welcome#index'

end

app/views/shared/_comments.html.erb
<% comments.each do |comment| %>
<div class= "comment-section">
  <div class="comment">

  <%=sanitize comment.content%>

  </div>
  <div class="comment-info">
    <%= link_to user_path(comment.user_id), data: { no_turbolink: true }, class: "thumb-link" do%>
      <%= image_tag comment.user.avatar(:thumb), class: "img-circle thumb" %>
    <%end%>
    <%= link_to comment.user.full_name, user_path(comment.user), class: "info-pad", data: { no_turbolink: true } %>
    <% if user_signed_in? %>
      <% if comment.user_id == current_user.id %>
        <%= link_to 'Delete Comment', comment_path(comment), method: :delete, class: 'info-edit' %>
      <% end %>
    <% end %>
    <span class="glyphicon glyphicon-calendar" style=padding-left:2%></span>
    <%= no_time(comment.created_at) %>
  </div>
</div>
</div>
<% end %>

app/views/shared/_follow.html.erb
<div class="stats">
  
    <strong class="stat">
      <%=link_to @user.following.count, following_user_path(@user.id)  %>
      
    </strong>
    Following |
  
  
    <strong class="stat">
      <%=link_to @user.followers.count, following_user_path(@user.id) %>
    </strong>
    Followers
  
</div>
<% unless @user.introduction.blank? %>
    <hr class="profile-break">
<p><%= @user.introduction %></p>
<% end %>

<% if user_signed_in? %>
<div class="follow-button-profile">
  <% if current_user.following?(@user) %>
    <%= link_to 'UnFollow', relationship_path(current_user.active_relationships.find_by(followed_id: @user.id)), method: :delete, class: "btn btn-lg btn-warning", remote: true %>
  <% else %>
    <%= link_to 'Follow', relationships_path(followed_id: @user.id), method: :post, class: "btn btn-lg btn-success", remote: true %>
  <% end %>
</div>
  
<% end %>

app/views/shared/_posts.html.erb
<%posts.each do |post| %>
  <article class="container post">
    <h1 class="header-link"><strong><%= link_to post.title, user_post_path(post.user, post) %></strong></h1>
    <%= post.content.html_safe%>
   </article>   
   <%= render 'posts/info', post: post %>
<% end %>

app/views/shared/_recent_comments_table.html.erb
<table class="table table-bordered table-striped recent-comments">
        <thead>
          <tr>
            <td  colspan="2" style="font-size:20px;">Recent Comments</td>
          </tr>
        </thead>
        <tbody>
          
            <% @comments.each do |comment| %>
              <tr>
                <td><%=link_to comment_preview(comment.content), user_post_path(comment.post.user, comment.post), title: "Commented on: #{comment.post.title} by #{comment.post.user.full_name}",  data: { toggle: 'tooltip', placement: "left" } %></td>
                <td><%= remove_time(comment)%></td>
              </tr>
          
            <% end %>
          
        </tbody>
        
</table>
<%= will_paginate @comments, param_name: 'comments_page', page_links: false, class: "digg_pagination" %>

app/views/shared/_show_follow.html.erb
<section class="container">
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-xs-12 col-md-4">
    <div class="user_info">
      <%= link_to @user, data: { no_turbolink: true } do %>
        <%=image_tag @user.avatar(:medium), class: "profile" %>
      <% end %>
      <div class="profile-name">
        <h1><%= @user.full_name %></h1>
        <span><b>Posts:</b> <%= @user.posts.count %></span>
      </div>
    </div>
    <div class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to user, class: "thumb-link" do%>
              <%=image_tag user.avatar(:thumb), class: "img-rounded" %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </aside>
  <div class="col-xs-12 col-md-8">
    <h3 class="text-center"><%= @title %></h3>
    <% if @users.any? %>
      <table class="table table-striped">
        <thead> <%= @title%></thead>
        <tbody>
        <%= render @users %>
        </tbody>
      </table>
      <%= will_paginate @users, page_links: false, class: "digg_pagination"%>
    <% end %>
  </div>
</div>
</section>

app/views/shared/_stats.html.erb
<div class="stats">
  
    <strong class="stat">
      <%= @user.following.count %>
    </strong>
    <%=link_to 'following', following_user_path(@user.id) %>
  
  
    <strong class="stat">
      <%= @user.followers.count %>
    </strong>
    <%=link_to 'followers', followers_user_path(@user.id) %>
  
</div>

app/views/shared/_table.html.erb
<table class="table table-bordered table-striped recent-posts">
        <thead>
          <tr>
            <td colspan="2" style="font-size:20px;">Recent Posts</td>
          </tr>
        </thead>
        <tbody>
          
            <% @posts.each do |post| %>
              <tr>
                <td><%=link_to post.title, user_post_path(post.user, post), title: content_preview(strip_tags(post.content)), data: { toggle: 'tooltip', placement: "left" } %></td>
                <td><%= remove_time(post)%></td>
              </tr>
          
            <% end %>
          
        </tbody>
        
</table>
<%= will_paginate @posts, param_name: 'posts_page', page_links: false, class: "digg_pagination" %>