config/routes.rb
Rails.application.routes.draw do


  get 'welcome/index'



devise_for :users, :controllers => { registrations: 'registrations' }, :path => '', :path_names => {:sign_in => 'login', :sign_up => 'signup', :sign_out => 'logout'}

  resources :users do
    resources :posts
    member do
      get :following, :followers, :edit_photo
    end
  end




  resources :relationships,  only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]

  

  get 'edit_photo', to: 'users#edit_photo'

  get 'friends_posts', to: 'relationships#index'

  post 'posts/show', to: 'comments#create'
   root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]


  belongs_to :user
  has_many :comments, dependent: :destroy
  
  validates :user_id, numericality: { only_integer: true }
  validates :title, presence: true
  validates :content, length: {minimum: 2, maximum: 10000}

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  load_and_authorize_resource
  
  def index
    @users = current_user.following.includes(:posts).reverse
    
    if @users.empty?
      render :index, flash: "Currently not following any users. Here's some of our most recents posts"
    end
    
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    
    if @post.save
      redirect_to user_post_path(@post.user, @post), notice: 'Post was successfully created'
    else
      render new_user_post_path, alert: 'Post not created. Please try again.'
    end
    
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.friendly.find(params[:id])
    @user = User.find(@post.user_id)
    @comments =@post.comments
    @comment = Comment.new
  end
  
  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])
    if @post.update(post_params)
      redirect_to user_post_path(@post.user, @post), notice: 'Post successfully updated'
    else
      render :edit, alert: 'Post was not updated. Please try again.'
        
    end
    
  end
  
  def destroy
    @post = Post.friendly.find(params[:id])
    @post.destroy
    redirect_to edit_user_path(current_user)
  end

  private
  
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
  
  #shorten content for title hover display
  def content_preview(post_content)
  
    preview = "#{post_content[0..75]}... *click for more*"
    return preview
  
  end

  #erase time off of created_at
  def no_time(date_time)
    date_time = date_time.to_s
    month = date_time.slice(5..6)
    date = date_time.slice(8..9)
    year = date_time.slice(0..3)
    
    return "#{month}/#{date}/#{year}"
    
  end
    

end

app/views/posts/_info.html.erb
<footer class="container post-info">
  <%= link_to user_path(post.user), data: { no_turbolink: true }, class: "thumb-link" do%>
    <%= image_tag post.user.avatar(:thumb), class: "img-circle thumb" %>
  <%end%>
  <%= link_to post.user.full_name, user_path(post.user), class: "info-pad", data: { no_turbolink: true } %>
  <% if user_signed_in? %>
    <% if post.user_id == current_user.id || current_user.admin? %>
      <%= link_to 'Edit Post', edit_user_post_path(post.user, post), class: 'info-edit' %>
    <% end %>
  <% end %>
  <span class="glyphicon glyphicon-calendar"></span>
  <span class="date"><%= no_time(post.created_at) %></span>
</footer>

app/views/posts/_post.html.erb
<% if can? :read, post %>
   <h1 class="header-link"><strong><%= link_to post.title, user_post_path(post.user, post) %></strong></h1>
   <%= post.content.html_safe %>
<% end %>
<% if can?:edit, post %>
   <%= link_to "Edit", edit_post_path(post) %>
<% end %>

app/views/posts/edit.html.erb
<section class="container">
<%=form_for @post, url: {action: "update"}, html: {class: "blog-title" } do |f| %>
   <% if @post.errors.any? %>
     <h3><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
     <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
     </ul>
   <% end %>
  <div class="form-group" id="new-title">
    <%= f.label :title %>
    <%=f.text_field :title, class: "form-control"%>
  </div>
  <div class="form-group" id="new-content">
    <%= f.label :content %>
    <%=f.text_area :content, class: "wysihtml5 form-control" %> 
  </div>
  <div class="form-group">
   <%= f.submit "Submit", class:"btn btn-lg btn-success"%> 
  </div>
<%end%>

</section>

<section class="container">


<h4>Delete this post?</h4>
<%=link_to "Delete Post", user_post_path(@post.user, @post), method: :delete, class: "btn btn-sm btn-danger",  data: { confirm: "Are you sure?", no_turbolink: true } %>

</section>
  
<script type="text/javascript">
  $(document).ready(function(){

    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5({'toolbar': {'color': true, 'smallmodals': true }});
    });

  })
</script>

app/views/posts/new.html.erb
<section class="container">
<%=form_for @post, url: {action: "create"}, html: {class: "blog-title" } do |f| %>
  <% if @post.errors.any? %>
    <h3><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="form-group" id="new-title">
    <%= f.label :title %>
    <%=f.text_field :title, class: "form-control"%>
  </div>
  <div class="form-group" id="new-content">
    <%= f.label :content %>
    <%=f.text_area :content, minlength: 50, maxlength: 10000, class: "wysihtml5 form-control new-post" %> 
  </div>
  <div class="form-group">
   <%= f.submit "Submit", class:"btn btn-lg btn-success"%> 
  </div>
<%end%>

</section>
  
<script type="text/javascript">
  $(document).ready(function(){

    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5({'toolbar': {'color': true, 'smallmodals': true }});
    });

  })
</script>

app/views/posts/show.html.erb
<article class="container post">
  <h1><strong><%=@post.title%></strong></h1>
  
  <%= @post.content.html_safe %>
  
  
  
  
</article>

<%= render 'info', post: @post %>

<section class="container new-comment">
  <% unless @comments.empty? %>
    <% if @comments.length == 1 %>
      <h3><%=@comments.length %> comment on "<%=@post.title%>" </h3>
    <%else %>
      <h3><%=@comments.length %> comments on "<%=@post.title%>" </h3>
    <% end%>
    <%= render 'shared/comments', comments: @comments %>
  <% end %>
  <hr></hr>
  <h3>Leave a Comment</h3>
  <% if signed_in? %>
      <%= form_for @comment, url: comments_path, html: {class: "comment-form"} do |f| %>
        <% if @comment.errors.any? %>
          <h3><%= pluralize(:comment.errors.count, "error") %> prohibited this post from being saved:</h3>
          <ul>
            <% @comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <div class="form-group">
          <%= f.label :comment %>
          <%= f.text_area :content, class: "form-control", required: true, maxlength: 2000 %>
        </div>
        <%=  f.hidden_field(:post_id, value: @post.id ) %>
        <%= f.submit "Post Comment", class:"btn btn-default", data: { no_turbolink: true } %>
      <% end %>  
  <% else %>
    <p>You must sign in to leave a comment</p>    
  <% end %>
</section>