config/routes.rb
Rails.application.routes.draw do


  get 'welcome/index'



devise_for :users, :controllers => { registrations: 'registrations' }, :path => '', :path_names => {:sign_in => 'login', :sign_up => 'signup', :sign_out => 'logout'}

  resources :users do
    resources :posts
    member do
      get :following, :followers, :edit_photo
    end
  end




  resources :relationships,  only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]

  

  get 'edit_photo', to: 'users#edit_photo'

  get 'friends_posts', to: 'relationships#index'

  post 'posts/show', to: 'comments#create'
   root 'welcome#index'

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to root_path do %>
          <%= image_tag "black.png", class: "navbar-brand" %>
        <% end %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to '<span class="glyphicon glyphicon-user"></span>&nbsp; Profile'.html_safe, user_path(current_user),  data: { no_turbolink: true }, class: "left-border" %></li>
          <li><%= link_to '<span class="glyphicon glyphicon-pencil"></span>&nbsp; New Post'.html_safe, new_user_post_path(current_user) %></li>
          <li><%= link_to('<span class="glyphicon glyphicon-log-out"></span>&nbsp; Logout'.html_safe, destroy_user_session_path,:method => :delete) %></li>
          <li class ="updates"><%= link_to "<span class='glyphicon glyphicon-bell'></span>".html_safe, friends_posts_path %></li
      </ul>
        <% else %>
          <li><%= link_to '<span class="glyphicon glyphicon-log-in"></span>&nbsp; Login'.html_safe, new_user_session_path, class: "left-border", data: { no_turbolink: true } %></li>
          <li><%= link_to '<span class="glyphicon glyphicon glyphicon-ok-sign"></span>&nbsp; Signup'.html_safe, new_user_registration_path %></li>
      </ul>
        <% end %>
    </div>
  </div> <!--container-->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Error Logs</title>
  <script src="https://use.typekit.net/mjn1urt.js"></script>
  <script>try{Typekit.load({ async: true });}catch(e){}</script>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body <%= yield(:body_attributes) %>>  
  <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
     <% elsif flash[:alert]%>
       <div class="alert"><%= flash[:alert] %></div>
  <% end %>
  
  <%= render "layouts/navigation" %>
  
  <%= yield %>
</body>
</html>